// old-website/src/lib/components/auth/login-form.svelte
<script lang="ts">
	import Icon from '@iconify/svelte';
	import { goto } from '$app/navigation';
	import { buildOAuthUrl, login } from '$lib/api/auth.js';
	import { Button } from '$lib/components/ui/button/index.js';
	import * as Card from '$lib/components/ui/card/index.js';
	import { Input } from '$lib/components/ui/input/index.js';
	import { Spinner } from '$lib/components/ui/spinner';
	import { StatusCodes } from 'http-status-codes';
	import {
		FieldGroup,
		Field,
		FieldLabel,
		FieldDescription
	} from '$lib/components/ui/field/index.js';
	import { validator } from '@felte/validator-zod';
	import { reporter, ValidationMessage } from '@felte/reporter-svelte';
	import * as z from 'zod';
	import { createForm } from 'felte';

	const loginSchema = z.object({
		email: z.email().max(255),
		password: z.string().min(8).max(255)
	});

	let redirectTo = '/';
	const url = new URL(window.location.href);
	redirectTo = url.searchParams.get('next') ?? '/';

	const { form, isSubmitting, setErrors } = createForm({
		extend: [validator({ schema: loginSchema }), reporter()],
		onSubmit: async (values) => {
				const res = await login(values.email, values.password);
				if (res.statusCode != StatusCodes.OK)
				   return (res.message || 'Login failed');
	  },
		onError: (errors) => {
			console.error('Form error:', errors);
			
		}
	});

	const handleGoogle = () => {
		window.location.href = buildOAuthUrl('google', redirectTo);
	};
</script>

<Card.Root class="mx-auto w-full max-w-sm">
	<Card.Header>
		<Card.Title class="text-2xl">Login</Card.Title>
		<Card.Description>Enter your email below to login to your account</Card.Description>
	</Card.Header>
	<Card.Content>
		<form use:form class="space-y-4">
			<FieldGroup>
				<Field>
					<FieldLabel for="email">Email</FieldLabel>
					<Input
						id="email"
						name="email"
						type="email"
						placeholder="m@example.com"
						autocomplete="email"
						required
					/>
					<ValidationMessage for="email" let:messages>
						{#if messages?.length}
							<FieldDescription class="text-destructive">
								{messages[0]}
							</FieldDescription>
						{/if}
					</ValidationMessage>
				</Field>

				<Field>
					<div class="flex items-center">
						<FieldLabel for="password">Password</FieldLabel>
						<a href="##" class="ms-auto inline-block text-sm underline"> Forgot your password? </a>
					</div>
					<Input
						id="password"
						name="password"
						type="password"
						autocomplete="current-password"
						required
					/>
					<ValidationMessage for="password" let:messages>
						{#if messages?.length}
							<FieldDescription class="text-destructive">
								{messages[0]}
							</FieldDescription>
						{/if}
					</ValidationMessage>
				</Field>

				<ValidationMessage for="FORM_ERROR" let:messages>
					{#if messages?.length}
						<FieldDescription class="text-destructive text-center">
							{messages[0]}
						</FieldDescription>
					{/if}
				</ValidationMessage>

				<div class="flex flex-col gap-3">
					<Button type="submit" class="w-full" disabled={$isSubmitting}>
						{#if $isSubmitting}
							<Spinner /> Loggin in...
						{:else}
							Login
						{/if}
					</Button>

					<Button type="button" variant="outline" class="w-full" onclick={handleGoogle}>
						<Icon icon="ri:google-fill" class="size-5" />
						Login with Google
					</Button>

					<FieldDescription class="text-center">
						Don't have an account?
						<a href="/auth/register">Sign up</a>
					</FieldDescription>
				</div>
			</FieldGroup>
		</form>
	</Card.Content>
</Card.Root>

// website/components/auth/login-form.tsx
"use client";

import React from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";

import { cn } from "@/lib/utils";
import { login } from "@/lib/api/auth";
import { buildOAuthUrl } from "@/lib/auth/oauth";
import { normalizeNextPath } from "@/lib/auth/next-path";
import { ApiError } from "@/lib/api/client";
import { applyServerFieldErrors } from "@/lib/api/error";
import { isPlainObject } from "@/lib/parsers/guards";
import {
  LoginFormValues,
  loginPayloadSchema,
  loginSchema,
} from "@/lib/schemas/auth";
import { FormDevTools } from "@/components/devtools/form-dev-tools";
import { Spinner } from "@/components/ui/spinner";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Field,
  FieldDescription,
  FieldError,
  FieldGroup,
  FieldLabel,
  FieldSeparator,
} from "@/components/ui/field";
import { Input } from "@/components/ui/input";

type LoginFormProps = React.ComponentProps<"div"> & {
  nextPath?: string;
};

export function LoginForm({ className, nextPath, ...props }: LoginFormProps) {
  const router = useRouter();
  const searchParams = useSearchParams();
  const resolvedNextPath = normalizeNextPath(
    nextPath ?? searchParams.get("next") ?? undefined,
  );
  const oauthRedirectTarget = resolvedNextPath ?? "/teams";

  const form = useForm<LoginFormValues>({
    resolver: zodResolver(loginSchema),
    defaultValues: {
      email: "",
      password: "",
    },
    mode: "onSubmit",
  });

  const onSubmit = async (values: LoginFormValues) => {
    form.clearErrors();

    const parsed = loginPayloadSchema.safeParse(values);
    if (!parsed.success) {
      form.setError("root", {
        type: "validate",
        message: "Invalid form data. Please try again.",
      });
      return;
    }

    try {
      await login(parsed.data);
      form.reset();

      router.replace(oauthRedirectTarget);
    } catch (error) {
      if (error instanceof ApiError) {
        if (error.status === 403 && isPlainObject(error.body)) {
          const message =
            typeof error.body.message === "string" ? error.body.message : "";

          if (message.toLowerCase().includes("email not verified")) {
            router.push(
              `/email-sent?email=${encodeURIComponent(values.email)}`,
            );
            return;
          }
        }

        const hasFieldErrors = applyServerFieldErrors(
          form.setError,
          error.body,
        );

        if (!hasFieldErrors) {
          form.setError("root", {
            type: "server",
            message:
              error.status >= 500
                ? "Server error. Please try again later."
                : error.message,
          });
        }

        return;
      }

      form.setError("root", {
        type: "network",
        message: "Network error. Please try again.",
      });
    }
  };

  const [isOAuthRedirecting, setIsOAuthRedirecting] = React.useState(false);

  const startGoogleOAuth = () => {
    if (isOAuthRedirecting) return;

    try {
      const oauthUrl = buildOAuthUrl("google", oauthRedirectTarget);
      setIsOAuthRedirecting(true);
      window.location.assign(oauthUrl);
    } catch (error) {
      setIsOAuthRedirecting(false);
      form.setError("root", {
        type: "oauth",
        message:
          error instanceof Error
            ? error.message
            : "Failed to start Google login.",
      });
    }
  };

  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting },
  } = form;

  return (
    <div className={cn("flex flex-col gap-6", className)} {...props}>
      <Card>
        <CardHeader className="text-center">
          <CardTitle className="text-xl">Welcome back</CardTitle>
          <CardDescription>
            Login with your Apple or Google account
          </CardDescription>
        </CardHeader>
        <CardContent>
          <form noValidate onSubmit={handleSubmit(onSubmit)}>
            <FieldGroup>
              <Field>
                <Button
                  variant="outline"
                  type="button"
                  className="w-full"
                  onClick={startGoogleOAuth}
                  disabled={isSubmitting || isOAuthRedirecting}
                >
                  {isOAuthRedirecting ? (
                    <>
                      <Spinner className="mr-2 h-4 w-4 animate-spin" />
                      Redirecting to Google...
                    </>
                  ) : (
                    <>
                      <svg
                        className="mr-2 h-4 w-4"
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 24 24"
                        aria-hidden="true"
                      >
                        <path
                          d="M12.48 10.92v3.28h7.84c-.24 1.84-.853 3.187-1.787 4.133-1.147 1.147-2.933 2.4-6.053 2.4-4.827 0-8.6-3.893-8.6-8.72s3.773-8.72 8.6-8.72c2.6 0 4.507 1.027 5.907 2.347l2.307-2.307C18.747 1.44 16.133 0 12.48 0 5.867 0 .307 5.387.307 12s5.56 12 12.173 12c3.573 0 6.267-1.173 8.373-3.36 2.16-2.16 2.84-5.213 2.84-7.667 0-.76-.053-1.467-.173-2.053H12.48z"
                          fill="currentColor"
                        />
                      </svg>
                      Login with Google
                    </>
                  )}
                </Button>
              </Field>

              <FieldSeparator className="*:data-[slot=field-separator-content]:bg-card">
                Or continue with
              </FieldSeparator>

              <Field>
                <FieldLabel htmlFor="email">Email</FieldLabel>
                <Input
                  id="email"
                  type="email"
                  placeholder="m@example.com"
                  aria-invalid={!!errors.email}
                  autoComplete="email"
                  {...register("email")}
                />
                <FieldError errors={[errors.email]} />
              </Field>

              <Field>
                <FieldLabel htmlFor="password">Password</FieldLabel>
                <Input
                  id="password"
                  type="password"
                  aria-invalid={!!errors.password}
                  autoComplete="current-password"
                  {...register("password")}
                />
                <FieldError errors={[errors.password]} />
              </Field>

              <Field>
                <FieldError errors={[errors.root]} />
                <Button
                  type="submit"
                  className="w-full"
                  disabled={isSubmitting}
                >
                  {isSubmitting ? (
                    <>
                      <Spinner className="mr-2 h-4 w-4 animate-spin" />
                      Logging in...
                    </>
                  ) : (
                    "Login"
                  )}
                </Button>
                <FieldDescription className="text-center">
                  Don&apos;t have an account? <a href="/signup">Sign up</a>
                </FieldDescription>
              </Field>
            </FieldGroup>
          </form>
        </CardContent>
      </Card>
      {process.env.NODE_ENV === "development" && (
        <FormDevTools control={form.control} />
      )}
    </div>
  );
}
