// website/src/routes/new-team/+page.svelte
<script lang="ts">
	import { createForm } from 'felte';
	import { validator } from '@felte/validator-zod';
	import { reporter, ValidationMessage } from '@felte/reporter-svelte';
	import { z } from 'zod';
	import { goto } from '$app/navigation';

	import * as Card from '$lib/components/ui/card';
	import { Input } from '$lib/components/ui/input';
	import { Button } from '$lib/components/ui/button';
	import { FieldGroup, Field, FieldLabel, FieldDescription } from '$lib/components/ui/field';
	import { createTeam } from '$lib/api/team';

	const schema = z.object({
		name: z.string().min(1, 'Team name is required').max(255, 'Team name is too long')
	});

	const { form, isSubmitting } = createForm({
		extend: [validator({ schema }), reporter()],
		onSubmit: async (values) => {
			try {
				const response = await createTeam(values.name);
				const teamId = response.data.id;
				await goto(`/${teamId}`);
			} catch (error) {
				return {
					FORM_ERROR:
						error instanceof Error
							? error.message
							: 'Unable to create team right now. Please try again.'
				};
			}
		}
	});
</script>

<div>
<div class="min-h-screen px-4 flex items-center justify-center">
	<Card.Root class="w-full max-w-md">
		<Card.Header>
			<Card.Title class="text-2xl">Create a new team</Card.Title>
			<Card.Description>Give your team a name. You can add members later.</Card.Description>
		</Card.Header>
		<Card.Content>
			<form use:form class="space-y-4">
				<FieldGroup>
					<Field>
						<FieldLabel for="team-name">Team name</FieldLabel>
						<Input
							id="team-name"
							name="name"
							type="text"
							placeholder="Acme SRE"
							autocomplete="organization"
							required
						/>
						<ValidationMessage for="name" let:messages>
							{#if messages?.length}
								<FieldDescription class="text-destructive">
									{messages[0]}
								</FieldDescription>
							{/if}
						</ValidationMessage>
					</Field>

					<ValidationMessage for="FORM_ERROR" let:messages>
						{#if messages?.length}
							<FieldDescription class="text-destructive text-center">
								{messages[0]}
							</FieldDescription>
						{/if}
					</ValidationMessage>

					<Field>
						<Button type="submit" class="w-full" disabled={$isSubmitting}>
							{$isSubmitting ? 'Creating…' : 'Create team'}
						</Button>
					</Field>
				</FieldGroup>
			</form>
		</Card.Content>
	</Card.Root>
</div>
</div>

// website/app/teams/new-team/page.tsx
"use client"

import { useRouter } from "next/navigation"

import { zodResolver } from "@hookform/resolvers/zod"
import { useForm } from "react-hook-form"

import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import {
  Field,
  FieldDescription,
  FieldError,
  FieldGroup,
  FieldLabel,
} from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { Spinner } from "@/components/ui/spinner"
import { createTeam } from "@/lib/api/teams"
import { ApiError } from "@/lib/api/client"
import { applyServerFieldErrors } from "@/lib/api/error"
import {
  type TeamFormValues,
  teamPayloadSchema,
  teamSchema,
} from "@/lib/schemas/team"

export default function NewTeamPage() {
  const router = useRouter()
  const form = useForm<TeamFormValues>({
    resolver: zodResolver(teamSchema),
    defaultValues: {
      name: "",
    },
    mode: "onSubmit",
  })

  const onSubmit = async (values: TeamFormValues) => {
    form.clearErrors()

    const parsed = teamPayloadSchema.safeParse(values)
    if (!parsed.success) {
      form.setError("root", {
        type: "validate",
        message: "Invalid form data. Please try again.",
      })
      return
    }

    try {
      const response = await createTeam(parsed.data)
      const team = response.data?.data
      form.reset()

      if (team?.id) {
        router.replace(`/teams/${team.id}`)
        return
      }

      router.replace("/teams")
    } catch (error) {
      if (error instanceof ApiError) {
        const hasFieldErrors = applyServerFieldErrors(form.setError, error.body)

        if (!hasFieldErrors) {
          form.setError("root", {
            type: "server",
            message:
              error.status >= 500
                ? "Server error. Please try again later."
                : error.message,
          })
        }

        return
      }

      form.setError("root", {
        type: "network",
        message: "Network error. Please try again.",
      })
    }
  }

  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting },
  } = form

  return (
    <div className="bg-muted flex min-h-svh flex-col items-center justify-center gap-6 p-6 md:p-10">
      <div className="flex w-full max-w-sm flex-col gap-6">
        <Card>
          <CardHeader className="text-center">
            <CardTitle className="text-xl">Create a team</CardTitle>
            <CardDescription>
              Choose a name for the team you want to manage
            </CardDescription>
          </CardHeader>
          <CardContent>
            <form noValidate onSubmit={handleSubmit(onSubmit)}>
              <FieldGroup>
                <Field>
                  <FieldLabel htmlFor="teamName">Team name</FieldLabel>
                  <Input
                    id="teamName"
                    type="text"
                    placeholder="Acme Inc."
                    aria-invalid={!!errors.name}
                    {...register("name")}
                  />
                  <FieldError errors={[errors.name]} />
                </Field>
                <Field>
                  <FieldDescription>
                    You can change this later in team settings.
                  </FieldDescription>
                </Field>
                <Field>
                  <FieldError errors={[errors.root]} />
                  <Button type="submit" className="w-full" disabled={isSubmitting}>
                    {isSubmitting ? (
                      <>
                        <Spinner className="mr-2 h-4 w-4 animate-spin" />
                        Creating team...
                      </>
                    ) : (
                      "Create team"
                    )}
                  </Button>
                </Field>
              </FieldGroup>
            </form>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
