// website/app/teams/[teamID]/monitors/page.tsx
import Monitor from "@/components/monitor/monitor";
import { Button } from "@/components/ui/button";
import { Plus } from "lucide-react";

export default function MonitorsPage() {
  return (
    <div className="flex flex-col gap-4">
      <div className="flex justify-between items-center">
        <div className="flex flex-col gap-1">
          <span className="text-xl font-bold">Monitor List</span>
          <span className="text-sm text-muted-foreground">
            All the monitor are down below
          </span>
        </div>
        <Button>
          <Plus />
          Add Monitor
        </Button>
      </div>
      <Monitor />
    </div>
  );
}

// old-website/src/routes/[teamID]/monitors/+page.svelte
<script lang="ts">
	import { Button } from '$lib/components/ui/button';
	import Icon from '@iconify/svelte';
	import Monitors from '$lib/components/monitor/monitors.svelte';

	/** @type {import('./$types').PageProps} */
	let { data } = $props();
</script>

<header class="flex flex-col gap-3">
	<div class="flex justify-between">
		<h1 class="text-2xl font-bold">Monitors</h1>

		<Button size="default" href="monitors/new">
			<Icon icon="lucide:plus" />
			New monitor
		</Button>
	</div>
	<p class="text-sm text-muted-foreground">
		Create and manage status pages to provide users with real-time updates.
	</p>
</header>

<div class="mt-7">
	<Monitors monitors={data.monitors} />
</div>
