// website/app/teams/[teamID]/status-pages/new/page.tsx
import Link from "next/link";

import { Button } from "@/components/ui/button";

export default async function NewStatusPage({
  params,
}: {
  params: Promise<{ teamID: string }>;
}) {
  const { teamID } = await params;

  return (
    <div className="flex flex-col gap-4">
      <div className="flex justify-between items-center">
        <div className="flex flex-col gap-1">
          <span className="text-xl font-bold">New Status Page</span>
          <span className="text-sm text-muted-foreground">
            Status page creation UI is coming soon.
          </span>
        </div>

        <Link href={`/teams/${teamID}/status-pages`}>
          <Button variant="outline">Back to list</Button>
        </Link>
      </div>
    </div>
  );
}

// website/src/routes/[teamID]/monitors/new/+page.svelte
<script lang="ts">
	import NewMonitor from '$lib/components/monitor/setting/basic-monitor.svelte';
import { Button } from '$lib/components/ui/button';
	import Icon from '@iconify/svelte';
</script>

<div class="flex flex-col gap-5">
	<div class="flex justify-between">
		<h1 class="text-2xl font-bold">New monitor</h1>

		<Button size="default" variant="ghost">
			<Icon icon="lucide:arrow-left" />
			Back to list
		</Button>
	</div>
	<NewMonitor />
</div>
