// website/src/lib/components/sidebar/app-sidebar.svelte
<script lang="ts">
	import NavMain from './nav-main.svelte';
	import NavUser from './nav-user.svelte';
	import TeamSwitcher from './team-switcher.svelte';
	import * as Sidebar from '$lib/components/ui/sidebar/index.js';
	import type { Team, User } from '../../types';
	import type { NavItem } from './type';

	const NavItems: NavItem[] = [
		{ title: 'Monitors', url: 'monitors', icon: 'lucide:monitor' },
		{ title: 'Status pages', url: 'status-pages', icon: 'lucide:layout-template' },
		{ title: 'Incidents', url: 'incidents', icon: 'lucide:alert-triangle' },
		{ title: 'Notifications', url: 'notifications', icon: 'lucide:bell' },
		{ title: 'Members', url: 'members', icon: 'lucide:users' },
		{ title: 'Settings', url: 'setting', icon: 'lucide:settings' }
	];

	let { user, teams }: { user: User; teams: Team[]; } =  $props();
</script>

<Sidebar.Root>
	<Sidebar.Header>
		<TeamSwitcher teams={teams}/>
	</Sidebar.Header>
	<Sidebar.Content>
		<NavMain items={NavItems} />
	</Sidebar.Content>
	<Sidebar.Footer>
		<NavUser user={user} />
	</Sidebar.Footer>
	<Sidebar.Rail />
</Sidebar.Root>

// website/components/sidebar/app-sidebar.tsx
"use client";

import * as React from "react";
import {
  Activity,
  Bell,
  LayoutTemplate,
  Settings,
  TriangleAlert,
  Users,
} from "lucide-react";

import { NavMain } from "@/components/sidebar/nav-main";
import { NavUser } from "@/components/sidebar/nav-user";
import { TeamSwitcher } from "@/components/sidebar/team-switcher";
import {
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarHeader,
  SidebarRail,
} from "@/components/ui/sidebar";
import { useParams, usePathname } from "next/navigation";

// This is sample data.
const data = {
  navMain: [
    {
      title: "Monitors",
      url: "/teams/{teamID}/monitors",
      icon: Activity,
      isActive: true,
    },
    {
      title: "Incident",
      url: "/teams/{teamID}/incidents",
      icon: TriangleAlert,
    },
    {
      title: "Notifications",
      url: "/teams/{teamID}/notifications",
      icon: Bell,
    },
    {
      title: "Status Pages",
      url: "/teams/{teamID}/status-pages",
      icon: LayoutTemplate,
    },
    {
      title: "Members",
      url: "/teams/{teamID}/members",
      icon: Users,
    },
    {
      title: "Setting",
      url: "/teams/{teamID}/settings",
      icon: Settings,
    },
  ],
};

function isActivePath(pathname: string, href: string) {
  const p = pathname.replace(/\/$/, "");
  const h = href.replace(/\/$/, "");

  return p === h || p.startsWith(h + "/");
}

export function AppSidebar({ ...props }: React.ComponentProps<typeof Sidebar>) {
  const params = useParams<{ teamID: string }>();
  const pathname = usePathname();

  const navItems = React.useMemo(() => {
    const teamID = params.teamID;
    const items = teamID
      ? data.navMain.map((item) => ({
          ...item,
          url: item.url.replace("{teamID}", teamID),
        }))
      : data.navMain;

    return items.map((item) => ({
      ...item,
      isActive: isActivePath(pathname, item.url),
    }));
  }, [params.teamID, pathname]);

  return (
    <Sidebar collapsible="icon" {...props}>
      <SidebarHeader>
        <TeamSwitcher />
      </SidebarHeader>
      <SidebarContent>
        <NavMain items={navItems} />
      </SidebarContent>
      <SidebarFooter>
        <NavUser />
      </SidebarFooter>
      <SidebarRail />
    </Sidebar>
  );
}
